@startuml rdt_initialization
!pragma teoz true

title Resampler/Delay Tracker Device Initialization

!$MCSLifeline = "#DDDDEE"
!$FHSFSPBackground = "#f0dbb7"
!$FSPCtrl = "#ffe680"
!$FSPCtrlLifeline = "#ffe680"
!$LowLevelDSBackground = "#cbecec"
!$LowLevelDS = "#99e6ff"
!$LowLevelDSLifeline = "#99e6ff"
!$LowLevelQ = "#78d0ed"
!$LowLevelQLifeline = "#78d0ed"
!$FWBackground = "#ffddee"
!$FWParticipant = "#f4aacc"
!$FWLifeline = "#f4aacc"

participant "Control Software (MCS)" as mcs

box "FHS-FSP" $FHSFSPBackground
participant "FSP Controller" as fspctrl $FSPCtrl
box "Resampler/Delay Tracker Device Server" $LowLevelDSBackground
participant "RDT Component Manager" as rdt_cm $LowLevelDS
participant "FODM Gen Library" as fodm_gen $LowLevelDS
queue "HO FIFO (Deque)" as ho_fifo $LowLevelQ
queue "FO FIFO (Deque)" as fo_fifo $LowLevelQ
end box
end box
box "Resampler/Delay Tracker FW" $FWBackground
participant "RDT Driver" as rdt_driver $FWParticipant
end box

/'================================
  UpdateDelayModels
================================'/
mcs -> fspctrl ++ $FSPCtrlLifeline: UpdateDelayModels()
fspctrl -> rdt_cm ++ $LowLevelDSLifeline: loadHODMs(model_array)
rdt_cm -> ho_fifo ++ $LowLevelQLifeline: extend(model_array)
rdt_cm <-- ho_fifo --
fspctrl <-- rdt_cm --: ResultCode.OK
mcs <-- fspctrl --: ResultCode.OK

/'================================
  ConfigureScan
================================'/
mcs -> fspctrl ++ $FSPCtrlLifeline: ConfigureScan()


/'================================
  Configure DS
================================'/
fspctrl -> rdt_cm ++ $LowLevelDSLifeline: configure()

rdt_cm -> rdt_driver ++ $FWLifeline: configure()
rdt_cm <-- rdt_driver --

fspctrl <-- rdt_cm --: ResultCode.OK


/'================================
  Start DS
================================'/
fspctrl -> rdt_cm ++ $LowLevelDSLifeline: start()

loop until started
  rdt_cm -> rdt_driver ++ $FWLifeline: status()
  rnote right of rdt_cm
    current_time: 1742500157.0
    running: False
    error_code: 0
    fodm_space_available: 4095
  endrnote
  rdt_cm <-- rdt_driver --

  loop while len(ho_fifo) > 0 and fodm_space_available > 0
    rdt_cm -> ho_fifo ++ $LowLevelQLifeline: pop()
    rdt_cm <-- ho_fifo --: HODM
    rdt_cm -> rdt_cm: Check HODM stop timestamp OK

    group if [HODM timestamp is OK]
      rdt_cm -> fodm_gen ++ $LowLevelDSLifeline: process(HODM)
      rdt_cm <-- fodm_gen --: FODM_array
      rdt_cm -> rdt_cm: Remove FODMs from FODM_array with invalid timestamps

      group if [len(FODM_array) > 0]
        rdt_cm -> rdt_cm: Create array FODMs_to_load
        loop for FODM in FODM_array
          rdt_cm -> fodm_gen ++ $LowLevelDSLifeline: CalcFodmRegisterValues(FODM)
          rdt_cm <-- fodm_gen --: register_values

          group if [len(FODMs_to_load) < fodm_space_available]
            rdt_cm -> rdt_cm: FODMs_to_load.append(register_values)
          else len(FODMs_to_load) >= fodm_space_available
            rdt_cm -> fo_fifo ++ $LowLevelQLifeline: append(register_values)
            rdt_cm <-- fo_fifo --
          end
        end

        rdt_cm -> rdt_driver ++ $FWLifeline: load_fodm(FODMs_to_load)
        rdt_cm <-- rdt_driver --: fodm_space_available

        group if [fodm_space_available = 0]
          rdt_cm -> rdt_driver ++ $FWLifeline: start()
          rdt_cm <-- rdt_driver --
        end
      end
    end
  end
end

fspctrl <-- rdt_cm --: ResultCode.OK
mcs <-- fspctrl --: ResultCode.OK

@enduml
