@startuml all_modes_controller_1
!pragma teoz true
allow_mixing

title AA2 FSP All Modes Controller (Option 1)

rectangle "MCS" as mcs
rectangle "FSP Device" as mcs_fsp_dev
rectangle "FSP CORR Subarray Device" as mcs_fsp_corr_dev
rectangle "FSP PSS Subarray Device" as mcs_fsp_pss_dev
rectangle "FSP PST Subarray Device" as mcs_fsp_pst_dev
rectangle "FSP All Modes Controller Device" as mcs_fsp_all_ctrl_dev
frame "Low-Level DS" as llds {
  label "etc..." as label
  rectangle "RDT Device" as rdt
  rectangle "Data Manager Device" as dm
  rectangle "16K Channelizer Device" as chan
  rectangle "4K PST Channelizer Device" as pstchan
  rectangle "PSS Corner Turn Device" as pssct
}

mcs --> mcs_fsp_dev
mcs_fsp_dev --> mcs_fsp_all_ctrl_dev

mcs_fsp_dev --> mcs_fsp_corr_dev
mcs_fsp_corr_dev --> mcs_fsp_all_ctrl_dev

mcs_fsp_dev --> mcs_fsp_pss_dev
mcs_fsp_pss_dev --> mcs_fsp_all_ctrl_dev

mcs_fsp_dev --> mcs_fsp_pst_dev
mcs_fsp_pst_dev --> mcs_fsp_all_ctrl_dev

mcs_fsp_all_ctrl_dev --> rdt: if CORR or PST
mcs_fsp_all_ctrl_dev --> dm: if CORR or PST
mcs_fsp_all_ctrl_dev --> chan: if CORR
mcs_fsp_all_ctrl_dev --> pstchan: if PST
mcs_fsp_all_ctrl_dev --> pssct: if PSS

@enduml
